apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: secretgen-controller.community.tanzu.vmware.com.0.5.0
  namespace: secretgen-controller
spec:
  refName: secretgen-controller.community.tanzu.vmware.com
  version: 0.5.0
  releaseNotes: "secretgen-controller 0.5.0 https://github.com/vmware-tanzu/carvel-secretgen-controller"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/secretgen-controller@sha256:a35fa688d302e39a93b4733af79d3bf63c924aa0dc4437dd6aca9c3bb1e9a353
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
