apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: secretgen-controller.community.tanzu.vmware.com.0.5.0
  namespace: secretgen-controller
spec:
  refName: secretgen-controller.community.tanzu.vmware.com
  version: 0.5.0
  releaseNotes: "secretgen-controller 0.5.0 https://github.com/vmware-tanzu/carvel-secretgen-controller"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/secretgen-controller@sha256:ce3f65a509a5502e1b68bda3fa9688e985adec3a77cb65438331fa6c0292384e
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
